### ISSUE TITLE
Convert RTCDefect annotation

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1030]
Tests use RTCDefect to convert a test class failed result to failed with defects or passed with defects.

We are not going to support RTC in Galasa as CICS TS are moving task management to GitHub.   Instead we are going to provide initial support for GitHub Issues.

As with RTCDefect, if the GH issue is still open,  then it can change the result,  if the issue is closed, the GitHubIssue is ignored.

Unlike RTCDefect,  GitHubIssue will need to support multiple githubs,  ie the public one and multiple GitHub Enterprise.

**Comment by jadecarino** [comment]
Update on this - I have been developing the GitHubIssue manager to support the GitHubIssue annotation. The manager can retrieve the current state of an Issue (open or closed) from the GitHub API and uses the state of the issue to determine whether to override the method result and the class result of a test.
Everything is working with public GitHub, but I haven't yet finished authenticating the requests so that the manager can access GitHub Enterprise.

**Comment by jadecarino** [comment]
Auth for Github Enterprise working.

**Comment by jadecarino** [comment]
Can I close this? @hobbit1983

**Comment by hobbit1983** [comment]
Have you merged the conversion plugin?

**Comment by jadecarino** [comment]
Yes :)

**Comment by jadecarino** [comment]
Plugin merged and tested
