### ISSUE TITLE
Provide support for the GitHubIssue annotation

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1031]
Add support for the GitHubIssue annotation, bearing in mind the following points:-

1. Template of the annotation ONLY is in github under workflow manager group
1. The RTCDefect code in JAT is in the RTC Manager https://github.ibm.com/eJAT/ejat_base/blob/prod/com.ibm.jat.rtc.manager
1. Use the GitHub api to retrieve the current status of the issue
1. Can be used on the class or method
1. Regex property can be used to narrow down the criteria, using same processing as existing RTCDefect
1. An Issue is either open or closed, ignore ZenHub capabilities
1. CPS will provide properties for the DEFAULT github location and credentials.  details below
1. CPS will provide properties for additional github locations and credentials, details below.
1. The URL provided needs to be converted to the api.xxx.xxx.xxx url.
1. log a message to indicate the current status of the issue and provide a URL direct to it.
1. Use gson bundle for json conversion
1. Create Pojos for the github API.
1. Do not use any github client to make this easier,  keep the dependencies of this Manager tiny.
1. Add unit tests,  use the galasa framework harness and mockito.   Enhance the harness to make it easier.  Write the manager methods in a way that makes unit testing easy.
1. IVTs not required.

CPS properties:-

githubissue.instance.DEFAULT.url=https://github.com         (make this value the default for the property)
githubissue.instance.DEFAULT.credentials=GITHUB            (make this value the default for the property)
githubissue.instance.DEFAULT.repository=galasa-dev/projectmanagement   (NO default, if it is missing from both CPS and the annotation, log warning message, but do not throw exception)

githubissue.instance.IBM.url=https://ibm.github.com 
githubissue.instance.IBM.credentials=GITHUB
githubissue.instance.IBM.repository=cics/cics-ts-tracking

githubissue.instance.url=https://ibm.github.com 
githubissue.instance.credentials=GITHUB
githubissue.instance.repository=cics/cics-ts-tracking

**Comment by jadecarino** [comment]
Update on this - I have been developing the GitHubIssue manager to support the GitHubIssue annotation. The manager retrieves the current state of an Issue (open or closed) from the GitHub API and uses the state of the issue to determine whether to override the method result and/or the class result of a test.
Everything is working with public GitHub, but I haven't yet finished authenticating the requests so that the manager can access GitHub Enterprise, that's on my list to do.
I am currently blocked as the bit of the framework in endOfTestClass and endOfTestMethod that takes the new result from the GitHub manager and actually sets that as the overriden test result has not been completed (it has a TODO comment) and currently just sets the result to Failed. The Result class needs to be finished so that a custom result can be set and/or Failed with Defects and Passed with Defects need to be added as possible states.

**Comment by jadecarino** [comment]
I've got auth for GHE working now. Have been updating the manager to use Result object instead of String as per the framework changes.

**Comment by jadecarino** [comment]
GitHubIssue manager is now at main. I have not written unit tests but I am testing the capability of the manager on the failing RSE tests.

**Comment by jadecarino** [comment]
Roll out of GitHubIssue manager on first customer: https://github.com/galasa-dev/projectmanagement/issues/1065
