### ISSUE TITLE
Get our automated tests running

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1189]

**Comment by jadecarino** [comment]
Automated tests stopped working when I changed velocity > velocity.engine.core (see https://github.com/galasa-dev/projectmanagement/issues/1085 )

inttests bundle cannot be resolved due to unsatisfied requirements.

Original stack trace:
26/09/2022 06:02:49.819 ERROR main dev.galasa.framework.BundleManagement.addResource - Unable to resolve dev.galasa.inttests/0.16.0
26/09/2022 06:02:49.819 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=dev.galasa.artifact)(version>=0.25.0)(!(version>=1.0.0)))
26/09/2022 06:02:49.820 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=org.apache.commons.lang3.reflect)(version>=3.11.0)(!(version>=4.0.0)))
26/09/2022 06:02:49.820 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=org.apache.commons.lang3.tuple)(version>=3.11.0)(!(version>=4.0.0)))
26/09/2022 06:02:49.820 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=org.apache.commons.lang3)(version>=3.11.0)(!(version>=4.0.0)))
26/09/2022 06:02:49.820 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=org.slf4j)(version>=1.7.0)(!(version>=2.0.0)))
26/09/2022 06:02:49.820 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=org.apache.velocity)(version>=2.3.0)(!(version>=3.0.0)))
26/09/2022 06:02:49.821 ERROR main dev.galasa.framework.TestRunner.runTest - Unable to load the test bundle dev.galasa.inttests
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "dev.galasa.inttests" from OBR repository

After adding org.apache.commons:commons-lang3:3.11 to Uber OBR this got rid of the unsatisfied commons-lang3.* requirements.

**Comment by jadecarino** [comment]
Changes made since:
- Added org.slf4j:slf4j-api:1.7.25 to Uber OBR
- Upgraded version of org.slf4j:slf4j-api:1.7.25 to 1.7.30
- Added dependency of org.apache.logging.log4j:log4j-slf4j-impl:2.17.1 to dev.galasa.framework.log4j2.bridge (build.gradle)
- Added dependency of org.apache.logging.log4j:log4j-slf4j-impl:2.17.1 to dev.galasa.framework (build.gradle)

**Comment by jadecarino** [comment]
- Added org.apache.logging.log4j:log4j-core:2.17.1 , org.apache.logging.log4j:log4j-api:2.17.1 and org.apache.logging.log4j:log4j-slf4j-impl:2.17.1 to Uber OBR

**Comment by hobbit1983** [comment]
Test are now running.  Uber obr shows slf4j-impl 2 failures around the docker tests to be investigated
