### ISSUE TITLE
create framework build-pr pipeline

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1194]

**Comment by jadecarino** [comment]
The gradle build task in the PR build pipeline for Framework failed:

Task :galasa-boot:jar FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':galasa-boot:jar'.
Entry META-INF/git.hash is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.5.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-framework-pr-370-skp2x?pipelineTask=gradle-build-framework&step=gradle-build

I have never come across this error before. We are using gradle version 7.5 instead of 6.8.2 which the current pipelines are using, but having had a google the approach to DuplicatesStrategy is the same in both versions. I have changed the version in the new pipeline to be 6.8.2 and have kicked off again to see if it makes a difference, but if not may need to investigate this error further.

**Comment by jadecarino** [comment]
Also, perhaps due to CPU limit on the new cluster, the build took 31 minutes before failing so is hard to make changes and run the pipeline to test, and get a quick feedback loop

**Comment by jadecarino** [comment]
Blocked as cannot run this pipeline without it timing out: https://github.com/galasa-dev/projectmanagement/issues/1234
