### ISSUE TITLE
Information repeated between different Managers

### ISSUE THREAD

**Issue by car0mac** [galasa-dev/projectmanagement#121]
zOS file Manager
This wording looks the same as the wording in z/OS Batch manager (except the Overview) 

zOS Manager 
This wording looks the same as the wording in z/OS Batch manager (except the Overview) 

I spoke to Dave about this and there is a problem to resolve here so raising as an issue after liaising with Mike.

**Comment by DavidXRoberts** [comment]
The doc is in dev.galasa.zos.manager project, but in different packages, i.e. 
    dev.galasa.zosbatch
    dev.galasa.zosconsole
    dev.galasa.zosfile
The zOS Manager is probably correct because it contains the doc for all 3 interfaces and
    z/OS Batch Manager
    z/OS Console Manager
    z/OS File Manager
should be removed from the list because they are not actually managers.

However, zOS Manager doc is incomplete because it doesn't yet describe it's annotations or have code snippets.   Also, the code snippets need to be better organised or somehow split up and grouped into manager functions, e.g. zOS (images and sysplexes, services etc.), Batch, Console and File
