### ISSUE TITLE
Documentation how to write a Galasa test

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#13]
1) "Best practice" on what you should and should not do in a Galasa test
2) How to find out about available managers
3) how to structure a test
...

**Comment by car0mac** [comment]
Have added this topic - https://next--galasa.netlify.com/docs/writing-galasa-tests
This covers points 1 and 3. 

Will add point 2 to point to the relevant place

**Comment by JonCollettIBM** [comment]
Hi Caroline, I took a quick look, my only comment is that in "Use existing features to help you", we've seen demonstrated @BeforeClass @Before @After etc. But, unless I am misremembering, I don't recalling seeing use of @StoredArtifactRoot in the IVT or simbank tests so far. We then go on and talk about @StoredArtifactRoot but at this point I don't really know what it is, because I haven't seen it used. Is this coming and one of the pieces of work that has yet to be done, perhaps from point 2 (am I jumping the gun)?

**Comment by CaroMac** [comment]
Hi Jon, I think you may have been looking at an old version of the txt - I had some problms with my builds and I've put up a bit more wording around Logger and StoredArtifactRoot. In fact they are both in the ProvisionedAccountTests sample but the latter is not called out specifically in the task docs - we are planning to add it. There is no @Before or After yet. I am raising an issue for a test to be created that use these. However, they are JUnit based so there is quite a few examples if folk google it. Hopefully the new wording for StoredArtifactRoot and Logger pointing folk at the simbank test will go far enough to explain it. I'm trying to keep this topic fairly conceptual but obv I don't want to call out something that then no-one understands. Let me know what you think!

**Comment by JonCollettIBM** [comment]
Now that the text has refreshed the reference to the SimBank ProvisionedAccountCreditTests makes it much better. I made the mistake of looking at the text rather than the code.

**Comment by CaroMac** [comment]
This is now completed - documented and reviewed here https://galasa.dev/docs/writing-own-tests and now live so will close this issue.
