### ISSUE TITLE
Release version 0.27.0

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1403]
## Story
As a galasa user I want to get the 0.27.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time

**Comment by jadecarino** [comment]
Network problems have blocked me from progressing with this release, as I haven't been able to finish the complete build of core Galasa. I also had to stop releasing the CLI as there was a bug found. This has been fixed in https://github.com/galasa-dev/cli/pull/81 but due to the same network problems, the PR build won't work.

As I haven't been able to progress, I tried to tick off some tasks later in the release pipeline, so that when we can progress these are already done, but there isn't much that can be done without previous stages being done first, other than both steps in the 'Bump to new version' section of the release docs:
- I have pushed changes to branch 'bump-28' of Framework, OBR, Eclipse and Isolated. These will need PRs and merging in.
- I have pushed changes to branch 'bump-0.28.0' of the CPS.properties in GitHub Enterprise. Again, will need a PR and merging in.

If someone picks up the release on Tuesday when I am at university, you will need to see if the network problems have resolved themselves so you can continue releasing. If so, the CLI needs recloning once the PR mentioned has been merged (Step 5 in Create branch and ArgoCD applications). I also have done the 'release' build up until Managers, so you will need to start from the OBR 'release' build.

**Comment by jadecarino** [comment]
Network problems faced: Unable to connect to external hosts. This is intermittent, sometimes works, sometimes doesn't, but multiple calls out to external hosts in each pipeline means it's likely to fail somewhere.
```
 Could not resolve host: github.com\n"
```
```
> development.galasa.dev: No address associated with hostname
```
```
https://repo.maven.apache.org/maven2/dev/galasa/galasa-maven-plugin/0.17.0/galasa-maven-plugin-0.17.0.pom: Network is unreachable (connect failed) -> [Help 2]
```

**Comment by jadecarino** [comment]
0.27.0 has been released. Any improvements to the release docs I have pushed to automation.
