### ISSUE TITLE
Authentication: User can log into Galasa ecosystem via a login panel.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1471]
## Story
As a galasasa testcase developer, I want to log into the galasa ecosystem so I can see a basic web UI.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background

User tries to launch into the Galasa UI application. They need to log in to see/use any function.

As part of the authentication epic, we want to use a browser to log into the galasa ecosystem web UI.

The web requests are routed to Dex

A successful login attempt allows a bearer token to be used to access a very basic Web UI web page.

Without the valid bearer token, you can't access the Web UI page, and it directs you to the login page.

### UI and REST interface work
- [x] Basic login panel with userid/password, and a Login button - provided by Dex.
- [x] Panel sends request to authenticate with Dex
- [x] Dex able to reply with bearer token/refresh token to the UI
- [x] Basic UI redirects to login panel if no bearer token present.
- [x] User id token stored in a cookie.
- [x] Re-authenticate token stored in a cookie.
- [x] JWT lifetime of 30 minutes (?) - configured in Dex
- [x] If JWT expires, send them back to the login panel.

### Test
- ~~IVT to test the UI using Selenium~~ scope moved. Raise another story for this part.

**Comment by eamansour** [comment]
The work required for this item is complete (see PR https://github.com/galasa-dev/webui/pull/6).

The webui needs to be installed into the ecosystem Helm chart in order to verify that the webui can communicate with Dex when running in a Kube cluster, which will likely only need adjustments to the environment variables provided in the Helm chart as opposed to making changes to the webui itself. The work to install the webui into the Helm chart is being tracked as part of issue https://github.com/galasa-dev/projectmanagement/issues/1481.
