### ISSUE TITLE
CLI : submit runs local to support hybrid CPS-on ecosystem configuration

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1505]

**Comment by hobbit1983** [comment]
Launcher follows this set of rules to find the bootstrap that it will use.
1.   If the `--bootstrap` flag has been set then this is used.
2.  If no bootstrap is explicitly provided then the users home directory + ".galasa/bootstrap.properties" is used as a default.  Note that this does not obey the GALASA_HOME environment variable that we have recently introduced.  --NOTE that this is also true for the overrides if they are not specified via the --overrides flag.

In either case the path provided is set as a URI and then loaded into a properties file.  This is then passed to whatever operation Launcher has been driven to perform.  i.e run Test, launch API etc.

Launcher:152 calls buildFramework which calls FelixFramework.buildFramework:210 passing the bootstrap properties that we calculated in the steps above

FelixFramework:79 creates a cache in the users home directory - again note this is not galasa_home and so this should be changed to use the new galasa_home environment variable.  The FelixFramework is then used to load the Galasa Framework.

FrameworkInitialisation:89 copies the content of the bootstrap properties over the override properties so that they will be available if a manager needs them.  The Framework then goes on to calculate the location of (in this order) - CPS,DSS,RAS and Creds.

The CPS is located by looking at the environment variable GALASA_CONFIG_STORE, if this is not available then the bootstrap property framework.config.store is used.  If both of these are missing then the GALASA_HOME env variable is used to calculate a cps.properties file and this is used instead

The location of the DSS is similar - looking first for a GALASA_DYNAMICSTATUS_STORE environment variable before then looking in the CPS (now it is known) for framework.dynamicstatus.store property before defaulting to galasa_home/dss.properties if nothing else can be found

The RAS is located in the same way as the DSS using GALASA_RESULTARCHIVE_STORE and framework.resultarchive.store cps property.  An extra property of framework.resultarchive.store.include.default.local is checked as a boolean to see if a local RAS should also be added regardless of what was located in the ENV_VAR/CPS

Credentials follows the same path.

1) Bootstrap properties if not specified in the --bootstrap get loaded from ~/.galasa/bootstrap ignoring the GALASA_HOME env var
2) Bootstrap properties are loaded over the top of overrides (thus the bootstrap being loaded from ~/.galasa/bootstrap can override something in GALASA_HOME/overrides.properties)
3) GALASA_CONFIG_STORE GALASA_DYNAMICSTATUS_STORE GALASA_RESULTARCHIVE_STORE GALASA_CREDENTIAL_STORE are all environment variables that can override CPS, overrides and bootstrap in configuring these locations
4) Once the CPS is loaded, DSS, RAS and CREDS can all be located from the CPS

In a local test that is using a remote ecosystem bootstrap we would expect the following:
1) The test should used the remote CPS and DSS but a local RAS and CREDS

2) Eclipse handled this by placing hardcoded locations for RAS and CREDS into the generated overrides file.  As long as these were not overridden again by the bootstrap then for this run only the hardcoded value would have been read as an override to the cps property

3) Outside of eclipse we want to be able to specify a local bootstrap property file so that we can specify local launch information like debug ports etc.  However we also want to specify the remote CPS, use the remote CPS to calculate the remote DSS.  But then override the values for the local RAS and CREDS

So - how do we solve this for environments outside of eclipse ... TBC

**Comment by hobbit1983** [comment]
My suggestion here is that the bootstrap properties are the core properties needed to start the galasa framework.  We are currently storing information in there such as debug ports which perhaps would be more useful in a galasactl.properties file held in the galasa_home folder.

This would allow  then for the CLI to look at this file to configure itself before moving on to launch the framework with bootstrap.properties.  In a purely local test, the bootstrap can be empty and allow the location of the CPS, RAS, DSS and creds to default to GALASA_HOME.  galasactl could insert overrides to specify the location of RAS and CREDS which for a local test would not be used but ....

In a hybrid test the bootstrap would point to a value in the ecosystem.  galasactl can still be configured with its own local file  and will still provide locations in overrides to the RAS and CREDS.  When the test runs the CPS and DSS will be located in the ecosystem and the RAS and CREDS will default to local files

When galasactl is executing runs submit (not local) then  it simply doesn't need to add the RAS and creds overrides.

so what work needs to be done ... TBC

**Comment by hobbit1983** [comment]
1) If we can check that the ecosystem isn't using the env vars GALASA_CONFIG_STORE GALASA_DYNAMICSTATUS_STORE GALASA_RESULTARCHIVE_STORE GALASA_CREDENTIAL_STORE then these should be removed from the logic.  They are not documented and are not used, but are confusing to be in the code

2)Loading the bootstrap from the default local file should default to GALASA_HOME and not `/.galasa

3)Create a new file in galasactl init for galasactl.properties to store the local CLI properties so they do not need to be in the bootstrap

4)Alter the logic in galasactl to pass on the bootstrap to a local test if needed and create the overrides to specify RAS and creds location for a local test

5) Revisit my latest PR in eclipse to ensure that this logic is still valid.  It is likely that we need to update that logic to add in RAS and CREDS overrides but get them to point to GALASA_HOME rather than `/.galasa

@techcobweb  That was quite an enjoyable piece of discovery.  When you have time can you cast your eye over my notes above and I would be interested in your thoughts on this.

**Comment by hobbit1983** [comment]
Moving to in Progress considering the investigation that has been performed.

**Comment by hobbit1983** [comment]
See the linked PR in framework for details of this change:

I've removed the use of environment variables to locate CPS, DSS, RAS and CREDS from the framework.  To avoid code duplication, I've moved the getGalasaHome method from framework init to launcher and allowed the launcher to locate galasa home and store it in the bootstrap properties, Framework init then just obtains this value passed in bootstrap props.  This seems to simplify the code a lot.

However it has caused some of the unit tests to fail so these need to be revisited before this can be merged.  I should also add unit tests into Launcher to cover the new function

**Comment by hobbit1983** [comment]
Will also need to remove the env vars from the helm installed.  From work with @eamansour although these are detailed in the helm chart they are not used and can be removed

**Comment by techcobweb** [comment]
Assigning 5 pints to this story.

**Comment by hobbit1983** [comment]
@techcobweb Yup agreed should have 5 pints before I look at refactoring the unit tests!!! 😂

**Comment by hobbit1983** [comment]
After conversation with @Jimbo4794 we think that our own integration tests might use this environment parameters when creating a child ecosystem as part of our integration tests.

**Comment by hobbit1983** [comment]
This is now mostly complete - Still need to review the environment variables as these might be used in our own integration testing.  Also need to review my eclipse PR

Small concern / testing required is what happens if the framework tries to create a DSS or CREDS file when it doesn't exist, but has been passed a URL i.e non local reference
