### ISSUE TITLE
Docker manager adhoc documentation

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#16]
Documentation above the reference material

**Comment by JonCollettIBM** [comment]
Thanks for removing the duplicate information. Just a few other, minor points/observations:

1. The text in Attribute:image... Change the sentence "It image name must not include the Docker Registry as this is provided in the CPS" to either "Its image name..." or "The image name...".
2. Attribute: DockerEngineTag if we don't need it, then consider removing it - at the moment it is accompanied by "Dont think we need this attribute".
3. When you click on the links "See DockerContainer and IDockerContainer to find out more" you get dropped into Java doc ,which has a totally different look and feel. Is this intentional? If it is, can we please consider opening these links in a new window? Currently, when either link is clicked it hijacks the window you are in and when you use the back button to return to the website, it dumps you out at the top of the Docker Manager section (meaning that you've lost your place and you the have to fiddle around navigating to where you were (not great in terms of usability).
4. In the Docker Registry URL CPS Property  where we mention https://registry.local.com or https://registry.hub.docker.com  these are currently clickable/linkable is that what we want? The first takes me to a page which is not found and the second to a generic "Build and ship an application anywhere" page. I suspect that we should just remove the ability to link/click. If clicked, they also hijack the window and the leave the user at the top of the doc on return,

**Comment by Michael-Baylis** [comment]
@Jimbo4794 I don't believe we need the dockerEngineTag at the moment as it is not used in any code.   Happy for me to delete?

**Comment by Michael-Baylis** [comment]
re 1.    will Change
re 2.   I will change from a markdown link to a html link so a new tab is opened.  Javadoc is supposed to be totally different.
re 4.  That is the browser being too helpful.  There is nothing we can do with this.  It is a code block so the browser should not really be converting to linkable items.

**Comment by Michael-Baylis** [comment]
we do need dockerEngineTag.  Will update the the docs

**Comment by Michael-Baylis** [comment]
All items on Jon's list has been corrected except no. 4 which we have no control over.

There is no additional documentation required.  We are not doing a Docker tutorial,   if you know Docker, all this will make sense.   If you don't know Docker,  then this isn't the place to learn.

Closing issue.

**Comment by JonCollettIBM** [comment]
@Michael-Baylis Just re-checking the doc, all have been done except for 1:
![image.png](https://images.zenhubusercontent.com/5dcbd1497938eb00019c3f31/8b8a353c-d02a-4dbe-a239-6aae24fb3afc)
