### ISSUE TITLE
API server's /bootstrap endpoint should return all bootstrap properties that have been set

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1635]
## Story
As a Galasa ecosystem developer, I want all of my bootstrap properties to be returned when hitting the `/bootstrap` endpoint, so that I don't need to find other ways to pass those properties into other services that already connect to the API server.

## Background
The API server's `/bootstrap` endpoint is hard-coded to only return the `framework.config.store`, `framework.extra.bundles`, `framework.testcatalog.url` properties. This should be returning all the properties that have been set.

Currently, the ecosystem's engine controller, resource monitor, and metrics services pass the API server's bootstrap URL using the `--bootstrap` flag (e.g. `--bootstrap http://<hostname>/bootstrap`), but also pass in environment variables to specify the locations of the CPS, RAS, DSS, and CREDs, which wouldn't need to be passed in if the `/bootstrap` endpoint returned the properties that have been set.

## Tasks
- [ ] Remove hard-coded references to the properties that `/bootstrap` returns
- [ ] Retrieve all bootstrap properties within the `/bootstrap` servlet and return them (unit tests implied)

**Comment by techcobweb** [comment]
I'm interested in why we need this now ? 
Long-term, we want to phase-out the bootstrap mechanism completely.

We should eventually only need the URL of the API server from outside the cluster...

From within the cluster it may be a different story of course.

I suspect it was originall coded this way so that more information can be shared internally with running pods, but not leak externally ?

@eamansour Can you please beef-up the explanation with more background information ?
