### ISSUE TITLE
CLI: Get property from non-existant namespace with name should say property doesn't exist.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1704]
```
./bin/galasactl-darwin-arm64 properties  get  --namespace framework --name xxxyyysss 
Error: GAL1096E: Could not query namespace results. Reason: '500 Internal Server Error'
```

As namespace xxxyyysss doesn't exist, and I used a specific name, why doesn't it tell me that the property does not exist ?

Should say that the property doesn't exist...

**Comment by Akyiaa** [comment]
The main problem here is that the name does not have a "." in it. Because the "." is not there, the name does not match the regex check expected by the api server.

In the following command, we receive the expected output:
```
./bin/galasactl-darwin-arm64 properties get --namespace framework --name dfbi.hjf                                                                                 
Total:0
```
This is a formatting error on the server side.
For a valid property name format, which does not exist, we will return a 404.
For a invalid property name format, we would throw a 400 Bad Request.
