### ISSUE TITLE
JMX files must be changed case by case, tests are not immutable

### ISSUE THREAD

**Issue by LukasMari** [galasa-dev/projectmanagement#172]

**Comment by rsomers1998** [comment]
Reopened due to properties for provisioned objects (Docker containers) cannot be added at runtime

Possibly add properties as a HashMap as well?

**Comment by Michael-Baylis** [comment]
I don't understand what the problem is with this.   There should be a standard galasa/jmeter image.  At runtime the JMX is modified with the correct properties and then copied to the container and then the container is started.

**Comment by rsomers1998** [comment]
This is correct, however at the moment there is no way to pass provisioned values (ie the host and ports of a docker container provisioned at runtime) due to the properties being given as an input stream. 

This could either be taking a file (which is fair for systems which do not change), or requires a properties file input stream to be created by the tester during the test (which seems like a lot of work which should be hidden in the manager).

I propose that the manager takes a 'key, value' hashmap object and can produce the properties file itself from this as it takes a lot of work away from the tester and allows for easier use of provisioned environments.

**Comment by Michael-Baylis** [comment]
The JMX file should be able to be parsed by Apache Velocity as it was in JAT,  is this not the case?
