### ISSUE TITLE
Should Zos3270Exception include InterruptedException?

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#177]
Zos3270Exception covers all manner of exceptions, but not InterruptedException, this means that a simple line like:
`terminal.type("CEBR " + queueName).enter().waitForKeyboard();`
causes a Zos3270Exception and an InterruptedException to be thrown and handled by the tester

**Comment by Michael-Baylis** [comment]
SonarQube influenced this setup because it considers InterruptException as a special exception and requires special handling.
InterruptedException within a Galasa engine will only really happen during an Abort.
In which case we need the IE to ripple all the way up and essentially stop the test.
However, I am happy for modify the manager to hide the IE,  not sure which is best.

**Comment by hobbit1983** [comment]
I think we should modify the manager, the tester doesn't know why an interrupted exception has been raised or the call that caused it.  The surrounding Zos3270Exception could contain the IE and the test could test for it

**Comment by Michael-Baylis** [comment]
Not sure what to do about this now.   enter and waitforkeyboard all have:-

ITerminal enter() throws KeyboardLockedException, NetworkException, InterruptedException;

KeyboardLockedException & NetworkException extend Zos3270Exception.

I suppose I could create a TerminalInterruptedException that extends Zos3270Exception,   so catches only need one catch they desire.

@hobbit1983 you happy with that?

**Comment by Michael-Baylis** [comment]
Throws TerminalInterruptedException now
