### ISSUE TITLE
Incorrect log message when ending a test if it's failed.

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#2046]
## Describe the bug
When a test fails it outputs an information message rather than an error message.   There is a section within the code that checks to see whether it's a pass or not.

## Steps to reproduce
Run a test that fails and it outputs:

```
04/11/2024 09:11:16.319 INFO  d.g.f.GenericMethodWrapper - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method my simple.test.HasFailed,type=Test
----------------------- ****************************************************************************************************
```

## Expected behavior
This should really be an ERROR.

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by techcobweb** [comment]
@adamcoulthard This is subjective no ? If a method passes, we output `Passed` so shouldn't we output `Failed` if it failed with an error ?

**Comment by adamcoulthard** [comment]
Sorry I should have been cleared the message is fine but it's logged as an `INFO` when it should be `ERROR`.  See my PR which switches them to `ERROR`.

**Comment by techcobweb** [comment]
modules/framework/galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/GenericMethodWrapper.java line 124

**Comment by techcobweb** [comment]
@adamcoulthard I guess it depends on your outlook, and definition of what an error is ?

- From the Galasa service's viewpoint, it's not an error, as nothing has gone wrong with the framework or system,  it's just that the test it was running failed for some reason.
- From the test author's perspective it is an error because a test failed, which is unexpected.

If we log errors for these things it will constantly look like the framework is having problems, when it's not.

We aren't doing it yet, but we will need to send all the pod logs to a central place and start analysing them, searching for errors. Testcase failures shouldn't show up as errors there I think.

This information is reported outside of the log anyway. How strongly do you feel it should be an error ?

Do we need two different logs ? one for framework and another for managers+test code ? Having the concerns inter-leaved is very helpful though.

**Comment by adamcoulthard** [comment]
Thanks @techcobweb ah I see what you are saying.

I think I would strongly push for this being changed because it allows for easy log parsing to identify that there has been an error in the test.  Attempting to parse the message to work out whether it's a failure is tricky and error prone for a simple change in galasa.  I'm already parsing the messages and using the INFO / ERROR / WARNING / DEBUG parts to colour code the output.  With this being and informational message this colour coding isn't working and so its easy for a tester to miss that an error has happened.

I noticed the problem because the log was so huge I couldn't easily find where the error was that made it fail.  Looking for certain keywords finds multiple instances of things .

From a users perspective it is an ERROR because the test has failed.  For the message specifically I don't think a user would think it was a framework failure because the execution immediately after it would explain what has happened with the test.

**Comment by techcobweb** [comment]
Ok. We will do this one shortly.

**Comment by techcobweb** [comment]
done in. 0.38.0
