### ISSUE TITLE
How to connect Galasa to application other than Simbank

### ISSUE THREAD

**Issue by Shalini174** [galasa-dev/projectmanagement#261]
Hi ,

I am trying to connect CICS setup on my zDnT with Galasa. I modified the overrides.properties with the instance name, IPv4 address and the port number. But when i do run configurations, the execution stops after the line : "Listener <init> Loading service: dev.galasa.simplatform.listener.WebServiceListener".

Please let me know if i am missing any steps/how to connect Galasa to my CICS region.

**Comment by Shalini174** [comment]
Hi Team,
Please suggest on the above issue.

**Comment by hobbit1983** [comment]
Hi.

That line you have listed is from the sim bank tutorial application.  That application will not run on the CICS region that you have running in your ZD&T image.  Updating the properties you refer to will allow you to write a Galasa test that connects to the CICS region in the ZD&T image.

Do you have a sample application installed in the CICS region on ZD&T that you are trying to test

**Comment by Michael-Baylis** [comment]
@Shalini174 To expand on what Will has said,   if you are connecting to your own CICS regions, then you are going to have to write your own tests as the SimBank ones will not work there.  You will also need to create more override.properties so that the Galasa managers know where to connect.

For your zD&T image you will need to define the following properties:-
```
zos.image.MV2C.ipv4.hostname=winmvs2c.hursley.ibm.com
zos.image.MV2C.telnet.port=23
zos.image.MV2C.telnet.tls=false
zos.image.MV2C.credentials=ZOS
```
This defines the image to the zos manager so it know the credentials and the 3270 port.
Change MV2C, winmvs2c.hursley.ibm.com, the port number and tls as appropriate.

In your test you will have a @ZosImage(),  where the tag default it PRIMARY, for latebinding (uppercased in 0.7.0), so you will need:-
```
zos.dse.tag.PRIMARY.imageid=MV2C
zos.dse.tag.PRIMARY.clusterid=DEFAULT
zos.cluster.DEFAULT.images=MV2C
```
That should sufficient.   If you want to submit batch jobs, be aware that you will need zOSMF on the image and on zD&T it runs slow as it is Java (we are looking at alternatives for zD&T).
You will need to define the zOSMF server to the zos sub managers:-
```
zosmf.server.MV2C.images=MV2C
zosmf.server.MV2C.hostname=winmvs2c.hursley.ibm.com
zosmf.server.MV2C.port=32070
```
If you need to change the default inputclass or msgclass:-
```
zosbatch.default.input.class=C
zosbatch.default.message.class=X
zosbatch.default.message.level=(0,0)
```
You will need credentials:-
```
secure.credentials.ZOS.username=IBMUSER
secure.credentials.ZOS.password=SYS1
```

**Comment by Shalini174** [comment]
@Michael-Baylis : my understanding is that even without writing test case and creating a project, i should be able to test if the connection with my zDnT server is getting established using the override.properties file and Run -> Run configurations option.
Please let me know if my understanding is incorrect and i need to create project and test case before establishing the connection to my zDnT.

**Comment by Michael-Baylis** [comment]
@Shalini174 Unfortunately you will need a basic test to drive the managers to do something, otherwise they will connect to anything.  The following is the most simple 3270 based test to allow you to "exercise" your configuration and see if it will connect to the 3270 terminals of your zD&T:-
```
package t;

import dev.galasa.Test;
import dev.galasa.zos.IZosImage;
import dev.galasa.zos.ZosImage;
import dev.galasa.zos3270.ITerminal;
import dev.galasa.zos3270.Zos3270Terminal;

@Test
public class TestConnect {

    @ZosImage(imageTag="PRIMARY")
    public IZosImage imageA;
    
    @Zos3270Terminal(imageTag="PRIMARY")
    public ITerminal terminalA;
    
    @Test
    public void testConnect() throws Exception {
        
        terminalA.waitForKeyboard().reportScreenWithCursor();
        
    }

}

```

**Comment by Shalini174** [comment]
@Michael-Baylis Thank you for the clarification. I will check my connectivity using the above test.

**Comment by Shalini174** [comment]
@Michael-Baylis : i am able to connect to my zDnT setup now. thank you :)

**Comment by Michael-Baylis** [comment]
Excellent
