### ISSUE TITLE
IZosConsoleCommand requestResponse() implementation

### ISSUE THREAD

**Issue by guitardozer** [galasa-dev/projectmanagement#290]
I would like the IZosConsoleCommand requestResponse() method to be implemented. We have use for a method to return console output that's not part of the immediate response (e.g. due to timeout, delay due to heavy system activity) or return additional console output after the immediate response.

**Comment by DavidXRoberts** [comment]
@guitardozer Not sure why I originally thought that requestResponse() hadn't been implemented. I have reviewed the code and run a couple of tests and it's working fine. 
When the command is issued, the immediate response is returned with a cmd-response-key and the value (which may be empty) is available via getResponse() method. This key is then used in the requestResponse() method and returns all responses since the initial response. Further calls to requestResponse() will retrieve all the responses since the call.

@CaroMac Looks like we need a doc update for this. Thanks

**Comment by DavidXRoberts** [comment]
I've updated the Javadoc for IZosConsoleCommand to hopefully explain the purpose of the the getResponse() and requestResponse() methods
