### ISSUE TITLE
Implement building the docker image from the Dockerfile

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#554]

**Comment by Michael-Baylis** [comment]
Sorry,  but I don't believe we will be providing this capability.   Building docker images is best left for a build system, not a test system.
Unless you can explain why you want a test to build a docker image?

**Comment by ArpanaKulenur** [comment]
Few usecases are:
1. Few parameters we cannot configure dynamically in CTG which needs to be preconfigured that means before bringing up the CTG container. So we need to pull CTG docker image, over that tune the parameters and rebuild it.
2. I need to build a application container which talks to CTG. Application container should be dynamically built based on testcase. I mean different testcases have different application to test.

**Comment by Michael-Baylis** [comment]
Hi,   we are 50:50 on whether we want to add build support to the docker manager.  Therefore I need to ask more questions on your use case.
Easy one first,  2).  We believe you should be passing the dynamic configuration information as environment variables rather than building a new image.  If there are files that need to be set, then a initialisation script should be run as part of start up that sets the files from the env vars before starting the test application.

As for 1), I am torn on this.  If you are saying your customers need to build a new image on top of the official CTG image to set these tuning parameters, then I can see the benefit.
However, if the building of the image a convience, then I would say it is better to create the container in the test,  send files to the container with the tuning parameters and then start the container.  This way you are testing with the actual official image rather than a modified version, ie the same image you will distribute.

**Comment by ArpanaKulenur** [comment]
We discussed on other ways to achieve without building the image, probably keeping the custom configuration files in persistent volume and then bringing the container up. As of now i will proceed by this way. Later if any scenario which really needs building the image then i will update and request accordingly.
Thank you.

**Comment by Michael-Baylis** [comment]
Cool,   I will close this issue down then.   If you decide you absolutely need it, please reopen or comment.
