### ISSUE TITLE
Galasa Eco system "waiting" and not able to execute tests 

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#555]
Resource Manager log provided to Michael Baylis to debug zos resman issue.

**Comment by nathandanielcassata** [comment]
Today, our Galasa tests suite execution is stuck in an infinite loop, and there is no clear reason why the test case cannot complete and is spawning a new execution. In the test case results, I can see that the test case is executed many times but does not indicate any failures for any of the test methods. This is a test case that we have run previously before updating to the 14-snapshot, and I am not sure what is causing the failure now.

This issue could be related to the test execution heartbeat since the slot processes are not cleaning up either. 

Please ping me on Slack if you need more information. 

@hbunchgithub, please feel free to add any details I might have missed regarding what you saw in the Ecosystem.

**Comment by hbunchgithub** [comment]
I captured a galasa_resource_management log and will be glad to provide it directly as it will not attach here.

**Comment by Michael-Baylis** [comment]
From what I am seeing,  at 07/01/2021 22:31:14.515 the etcd server stopped responding to the ResMan.   After that, it seems hit or miss on whether some of the Manager's resman routines carried on or not.   In this case the zOS SlotResourceMonitor got stuck.
Any tests "lost" would mean the zos slots wouldn't be cleaned up.

I am desperate to find these problems as it is vital to the process of hardening Galasa so it can survive the temporary remove of a server and can carry on when it returns.  This acceptance of temporary loss of service seems to be the way the cloud works.

I did hope that the JETCD client would have automatically recovered from a timeout or loss of communication, but it appears not to be doing so.  So maybe I need to add some health checking and recovery to the etcd services in Galasa.

For you, for the moment, maybe it would help to add some health checking to the resource management container (all others will suffer the same).  If it detects known errors,  then force a restart.    This is something we need to add to Galasa properly, though would like it to be more elegant, and certainly don't have time to do it.

**Comment by Michael-Baylis** [comment]
Also,  force a restart once a day, maybe.

**Comment by Michael-Baylis** [comment]
I have logged on to the server,  all looks good.  I forced restarted the docker resman, just to be sure.
I am waiting for a failure to see what we can do to autorecover if there is a comms break to etcdctl

**Comment by Michael-Baylis** [comment]
I believe we have tracked this down to an issue with RAS master doc integrity check #560  and reset not freeing resources #561.
If this is not the case, please reopen.
