### ISSUE TITLE
Credential management: add the Vault extension

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#881]
Enhancement request to be able to manage credentials in a production ecosystem which is managed centrally. 
I need to set and be able to alter credentials, which I can currently do locally, in an ecosystem managed by the Galasa team. Currently I'd have to ask one of the team to set/update credentials whenever a change was necessary.

Talking with Michael B. the preferred solution for credentials would be to add the Vault extension to the credentials so they can grant, inside the vault, an area for me (or whoever) to manage.  Then all the Galasa team would need to do is add the linking cps properties and won’t need to change anything after that.

**Comment by techcobweb** [comment]
The preferred solution is to enable the setting and getting of credentials over the command-line and REST interface. How Galasa stores the secrets internally is up to it, so long as the secrets are encrypted and conform to security standards.

We want to introduce role-based security also, initially so that 'admins' can see/set secrets, and 'authorised normal users' can use them from the test cases they kick off.
We don't really want Galasa to get into fine-grained auth groups who can only see a number of secrets, but not the rest. That would be unnecessarily complex.

The overall solution is to create a separate tool which takes secrets from the IBM Cloud Secrets Manager, and synchronises them with the Galasa ecosystem runtime every 10 minutes or so. That way, the IBM cloud can be the thing you change, which in turn causes the Galasa ecosystem to change.

The IBM Cloud secrets manager has 'areas' of secrets namespace which can be managed by different people.

Managing secrets externally like this would satisfy your requirements @jasonrhughes ?

**Comment by jasonrhughes** [comment]
Yes, that sounds perfectly acceptable - thank you.
Things have moved on since I opened this; we don't currently have a need for this enhancement, but we're likely to want to make use of it at some point in the future. 
I'm happy for this issue to be closed, unless you'd prefer to keep open for tracking.

**Comment by techcobweb** [comment]
Closing the issue, as we have other stories to track the solution we are aiming for, as described in the comments.
eg:
- Ecosystem CREDS to be synchronized with those stored in IBM Cloud Secrets Manager
[#1796](https://github.com/galasa-dev/projectmanagement/issues/1796)
- Credentials stored in ETCD should be encrypted #1467
