### ISSUE TITLE
Generate Manager Reference documentation

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#9]
Create templates and programs to generate the Manager reference information direct from the source code and update the doc site.

Will need automatically submit pull requests when run.

**Comment by Michael-Baylis** [comment]
Complete.

**Comment by JonCollettIBM** [comment]
I'm not sure if I am supposed to put doc observation in here, but I guess people will get notified. So here goes:
1. "Galasa Ecosystem Manager" the doc is OK, but it mixes tenses in a few places, making it hard to discern what is provided in the alpha versus what might be coming in the future. For example, "will provide ....." instead of "provides ....".
2. Kubernetes Manager" I have an issue with all of the links hijacking the reader's current window when clicked (instead of opening a new tab), meaning that on return (from the javadoc etc.) the reader is dumped back at the top of the document, forcing them to navigate back to where they were. In this exmaple it also applies to the links to YAML files.
